services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-backend
    environment:
      SPRING_DATASOURCE_URL: ${PROD_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${PROD_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PROD_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: never
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"

      #Ajustes de Auth0 para entornos.
      auth0.domain: ${AUTH0_DOMAIN}
      auth0.m2m.clientId: ${AUTH0_CLIENT}
      auth0.m2m.clientSecret: ${AUTH0_CLIENT_SECRET}
      auth0.roleId: ${AUTH0_ROLEID}

    ports:
      - "8080:8080"    
    networks:
      - monorepo-net  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    environment:
      NODE_OPTIONS: "--max-old-space-size=2048"
      API_BASE_URL: http://spring-backend:8080
    deploy:
      resources:
        limits:
          memory: 3072m
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - monorepo-net

#curler:
    # Imagen ligera que contiene la herramienta curl
 #   image: curlimages/curl
    # Esta herramienta no necesita correr siempre, solo para diagnóstico
  #  command: ["sleep", "infinity"]
networks:
  monorepo-net:
    driver: bridge
