INSERT INTO FIELD(AREA, FIELD_TYPE) VALUES(10,'tenis');
INSERT INTO FIELD(AREA, FIELD_TYPE) VALUES(12,'tenis');
INSERT INTO FIELD(AREA, FIELD_TYPE) VALUES(14,'futbol');
INSERT INTO FIELD(AREA, FIELD_TYPE) VALUES(15,'futbol');
INSERT INTO FIELD(AREA, FIELD_TYPE) VALUES(16,'padel');
INSERT INTO FIELD(AREA, FIELD_TYPE) VALUES(20,'padel');
INSERT INTO USERS(BIRTHDATE, DOCUMENT_NUMBER, LASTNAME, USERNAME, EMAIL, TELEPHONE) VALUES('03/11/1999', 3883, 'Acosta', 'Moises', 'moisesacosta8@gmail.com', 7268);
INSERT INTO USERS(BIRTHDATE, DOCUMENT_NUMBER, LASTNAME, USERNAME, EMAIL, TELEPHONE) VALUES('03/11/1999', 5883, 'Alvarenga', 'Moises', 'aa20029@ues.edu.sv', 7168);
INSERT INTO CUSTOMER VALUES(1, '03/11/2025', 1);
INSERT INTO EMPLOYEE VALUES(2, '05/11/2025', 'GERENTE', 2)
